### ISSUE TITLE
Many obsolete functions in ~/matlab/LAST/LAST_OCS/+obs/+util

### ISSUE THREAD

**Issue by noralinn** [PolishookDavid/LAST_OCS#15]
I'm suspecting that several functions in ~/matlab/LAST/LAST_OCS/+obs/+util are obsolete. It would be good to check whether they can be removed. (This file list is for the j2000inheader branch.)

**The ones that are definitely used are:**

- ./+align/alignCameraRotation.m - used for camera rotation and telescope alignment
- ./+align/polarAlignPole.m - used for polar alignment
- ./+align/moveToXY.m - used for setcoordinate
- ./+align/pointingModel.m - used to record pointing model
- ./+observation/obsByPriority.m - observing script

**Remaining files, check whether they are used:**
- ./+align/polarAlignOffline_drift.m
- ./+align/find_mount_mechanical_pole.m  
- ./+align/polarAlignOffline_polaris.m
- ./+align/moveMountPoleWhileImage.m
- ./+align/randomMotion.m

- ./+image/astrometry_center.m  
- ./+image/imageFocus.m  
- ./+image/image_quality.m  
- ./+image/plot_image_quality.m

- ./+observation/observe.m - replaced by obsByPrio? 
- ./+observation/observe_targets.m - replaced by obsByPrio?
- ./+observation/run.m  
- ./+observation/test_motion.m

- ./+pointing/allSkyPointingOffset.m  
- ./+pointing/gather_alignment_images.m

- ./+tools/minimum123.m - used by old focus loop
- ./+tools/parabolicInterpolation.m - used by old focus loop

**Comment by EastEriq** [comment]
As there seems to be no cooperation on this, I moved some files to an obsolete/ subtree. Some need may resurface the next time we have to install a new mount or move to the new building, as we will discover that the former scripts for polar alignment and buildup of the pointing model may need reworking. But we'll deal with them when we are there.
