### ISSUE TITLE
default `focusLoop` as blocking also when run in master

### ISSUE THREAD

**Issue by EastEriq** [PolishookDavid/LAST_OCS#23]
By polling the slaves for commandExecuting, or by looking at the log file, or whatever. That way a superunit won't be able to send a new command to the master before completion, and `Unit.GeneralStatus` can be updated progressively.
The current nonblocking behavior could be left as an option.

**Comment by EranOfek** [comment]
one issue with this is that if there is a problem in the focus loop, then
we won't have a simple way to stop it.

**Comment by EastEriq** [comment]
> one issue with this is that if there is a problem in the focus loop, then we won't have a simple way to stop it.

You have it, `Unit.abort`. If it doesn't work for you, report it as a bug.

**Comment by EastEriq** [comment]
TODOs:
- add time started and ended information in `Unit.FocusData` and use it in `obs.util.observation.plotFocusData`
- consider also adding plots of the fit parabolas, identical to what originally plotted by `focusTelInSlave`
- see issues in #36

**Comment by EastEriq** [comment]
save "consider also adding plots of the fit parabolas" (see https://github.com/PolishookDavid/LAST_OCS/issues/36#issuecomment-2283481189), this can be closed
