### ISSUE TITLE
All _HA information in FITS header is correct only at the start of an exposure

### ISSUE THREAD

**Issue by EastEriq** [PolishookDavid/LAST_OCS#29]
With the new header scheme implemented in branch gledmagicwater, we construct `Unit.UnitHeader` just before commanding the cameras to expose. This part of the header has now all the mount related information, including the application of the pointing model. This has the huge advantage that the computation is done only once, and there is no need for each of the slaves to query the master again. This saves time and headaches in queries backfiring; in particular, it allows continuous saving with shorter exposure times, because less messaging is involved. However, the information is strictly correct only at the time of computation. For long sequences, HA drifts away at tracking speed, and becomes soon wrong (we never used anything but sidereal tracking, but in principle it could be a different speed). Even RA is correct only upon the assumption that the mount tracking is good and strictly sidereal.

I thought at this after closing #12.

Perhaps we should:
- construct a part of UnitHeader including only _RA (apparent, equinox of date, distorted, etc.) and tracking speed before exposing, as now;
- calculate the resulting _HAs in the slaves using the value of RA and the image start time, upon the assumption that all the flavours of _HA evolve at the same tracking speed (differential corrections due to the pointing model are second order)

Not doing that, we have to inform the pipeline consumers that HAs need to be recomputed, using the initial HA, the tracking speed and the timing information written in the header. Too prone to error.

**Comment by EastEriq** [comment]
ditto for Alt and Az, they change along with tracking

**Comment by EranOfek** [comment]
functions that can be used:
celestial.convert.convert_ha
celestial.coo.hadec2azalt

**Comment by EastEriq** [comment]
yes those are the functions used in the mount code as well, the computation will need to be duplicated in the slave part of the construction of the header (`unitCS.constructTelescopeHeader`), after the master part only read the physical Ra and Dec. The disadvantage of duplication is duplication of the code and risk of divergence, but the advantage is less elementary queries to the mount controller (for simplicity of the code, each time one of {HA,Dec,Az,Alt,RA} is asked, both controllers are queried again)

**Comment by EastEriq** [comment]
Implementation with the last commit looks ok to me at first inspection, but I need confirmation of from the observers and image processors. Waiting to close till I get feedback from them, hopefully already next week.

**Comment by EranOfek** [comment]
Can you please summarize the modification (e.g., are you assuming RA is
constant and you are using something like convert_ha to recalculate the HA?)
If you can send a header example with the relevant keywords, I can inspect
it.

**Comment by EastEriq** [comment]
The correction is: all RA, HA, Dec (apparent-distorted-Jwhatsissname) are first computed at the time takeExposure is called, then corrected according to the time at which the exposure actually started, according to
```
       RAcorrection=(TRK_RA/3600-360/86164.0905)*DeltaTsec;
       HAcorrection=(TRK_RA/3600)*DeltaTsec;
       DECcorrection=(TRK_DEC/3600)*DeltaTsec; % in degrees
```
It's a first order correction because it assumes that d(RA_app/dist/J)/d RA_mount =1 etc.
You can look up the modification in the two file affected by the last commit. 
I'm attaching anyway two headers here, if you can inspect them that would be very helpful.
[H1.txt](https://github.com/user-attachments/files/16324786/H1.txt)
[H2.txt](https://github.com/user-attachments/files/16324787/H2.txt)

**Comment by EranOfek** [comment]
I suspect that you do not update the LST.
LST should increase with the sidereal rate:
(360/86164.0905)*DeltaTsec

and therefore (LST-RA)  should be equal to HA.

**Comment by EastEriq** [comment]
I don't even write in the header LST. Should I?

In any event, isn't that equivalent to my computation?

**Comment by EranOfek** [comment]
The LST is written to the header by the camera, so you are writing it...
Your computation looks good, but the only way I can check its consistency
(assuming I have only the header) is by using the LST.
By the way, are you also updating the DATE-OBS keyword?

**Comment by EastEriq** [comment]
That LST is the one computed according to the exposure start time. Ditto DATE-OBS. The computation of DeltaT is done using JD, thus avoiding modulo 24h issues.

I'm basically convinced by my approach, given the constraint of not wanting to access mount information in the telescope slaves. The doubts are:
- to which extents the errors in assuming that HA_anything(t1)~=HA_anything(t0)+(t1-t0)*tracking_HA are negligible (ditto for RA, Dec - i.e. neglecting that corrected coordinates are functions of HA, Dec, and cross and higher order terms may be significant
- which altitude to pass to `celestial.coo.hardie` to get the true airmass

**Comment by EranOfek** [comment]
A consistency between lst and ha/ra of about 10 arcsec is good enough.

Re airmass, this is not very accurate, so dont worry abou it.
Note that hardie input is the zenith fistance in radians

**Comment by EranOfek** [comment]
Re HA and LST:

HA = LST - RA, and this should be correct for any set of HA and RA in the
smae reference frame.
For example, ADHA = LST - ADRA and M_JHA = LST - M_JRA,...

Re airmass, this altitude corresponds to the mount altitude, where the
mount altitude should have been calculated using M_RA,M_Dec (and not M_JRA,
M_JDec) - I guess this is what you are doing.

**Comment by EastEriq** [comment]
> Re HA and LST: HA = LST - RA, and this should be correct for any set of HA and RA in the smae reference frame. For example, ADHA = LST - ADRA and M_JHA = LST - M_JRA,... 

I'm **not** using LST to compute HA_whatever from RA_whatever (except for M_HA and M_RA). 
I'm using delta(M_RA) to update all other RA_whatever, as an approximation. That is the whole point.

>Re airmass, this altitude corresponds to the mount altitude, where the mount altitude should have been calculated using M_RA,M_Dec (and not M_JRA, M_JDec) - I guess this is what you are doing.
 
I'm not. I'm using ADRA and ADDEC. My rationale is that the pointing model should be accounting for mount flexure (not nutations, librations, precession of equinoxes, etc), so that the true angle with the zenith should not be computed according to what the encoders say (M_HA, M_DEC) but according to what it is established that the mount is looking at. Overzealous?

**Comment by EranOfek** [comment]
ok

**Comment by EastEriq** [comment]
Verified by Simone, headers should be ok now
